"""Regression tests for the pinned Airplanes.live map UI bundle."""

import hashlib
import json
import os
import re
import runpy
import stat
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "deploy" / "prepare-map-ui.py"
MANIFEST = json.loads((ROOT / "deploy" / "map-ui.json").read_text(encoding="utf-8"))
ARCHIVE_ENV = os.environ.get("ADSB_MAP_UI_ARCHIVE")
PINNED_ARCHIVE = Path(ARCHIVE_ENV) if ARCHIVE_ENV else None


# hash a prepared source artifact
def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        # stream large source artifacts
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


# execute the public preparation interface
def prepare(output: Path, archive: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["python3", str(SCRIPT), str(output), str(archive)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        umask=0o077,
    )


# verify immutable bundle generation behavior
class MapUiPreparationTests(unittest.TestCase):
    # bind every generated byte and integration target deterministically
    def test_bundle_digest_is_reproducible_and_tracks_content_and_wiring(self):
        preparer = runpy.run_path(str(SCRIPT))
        with tempfile.TemporaryDirectory() as directory:
            roots = [Path(directory) / "first", Path(directory) / "second"]
            # build equivalent trees in separate locations
            for root in roots:
                root.mkdir()
                (root / "asset.js").write_text("asset", encoding="utf-8")
                (root / "config.js").symlink_to("/image/config.js")
                (root / "version.json").write_text("ignored one", encoding="utf-8")
                (root / "provenance.json").write_text("ignored two", encoding="utf-8")

            digest = preparer["bundle_digest"]
            first_digest = digest(roots[0])
            self.assertEqual(first_digest, digest(roots[1]))

            (roots[1] / "asset.js").write_text("changed asset", encoding="utf-8")
            self.assertNotEqual(first_digest, digest(roots[1]))
            (roots[1] / "asset.js").write_text("asset", encoding="utf-8")
            (roots[1] / "config.js").unlink()
            (roots[1] / "config.js").symlink_to("/image/changed-config.js")
            self.assertNotEqual(first_digest, digest(roots[1]))

    # stop a response that exceeds the pinned byte count
    def test_download_rejects_oversize_stream_in_bounded_read(self):
        preparer = runpy.run_path(str(SCRIPT))
        response = mock.MagicMock()
        response.__enter__.return_value = response
        response.read1.return_value = b"12345"
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "archive.tar.gz"
            with mock.patch("urllib.request.urlopen", return_value=response) as urlopen:
                with self.assertRaisesRegex(ValueError, "size"):
                    preparer["download_archive"]("https://example.test/archive", destination, 4)
        self.assertLessEqual(response.read1.call_args.args[0], preparer["DOWNLOAD_CHUNK_BYTES"])
        self.assertEqual(preparer["DOWNLOAD_IO_TIMEOUT_SECONDS"], urlopen.call_args.kwargs["timeout"])

    # enforce a total deadline across individually bounded reads
    def test_download_rejects_stream_past_total_deadline(self):
        preparer = runpy.run_path(str(SCRIPT))
        response = mock.MagicMock()
        response.__enter__.return_value = response
        response.read1.return_value = b"x"
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "archive.tar.gz"
            with mock.patch("urllib.request.urlopen", return_value=response):
                with mock.patch("time.monotonic", side_effect=[0.0, 0.0, 121.0]):
                    with self.assertRaisesRegex(TimeoutError, "deadline"):
                        preparer["download_archive"]("https://example.test/archive", destination, 4)

    # require exactly one reviewed aggregator declaration
    def test_local_receiver_patch_rejects_missing_or_duplicate_source(self):
        preparer = runpy.run_path(str(SCRIPT))
        with tempfile.TemporaryDirectory() as directory:
            early = Path(directory) / "early.js"
            # reject both missing and ambiguous source declarations
            for source in ("const unrelated = true;\n", "let aggregator = true;\nlet aggregator = true;\n"):
                early.write_text(source, encoding="utf-8")
                with self.assertRaisesRegex(ValueError, "exactly once"):
                    preparer["wire_local_receiver"](early, MANIFEST["local_patches"][0])

    # reject an archive before extraction or output publication
    def test_rejects_archive_with_wrong_checksum(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            archive = root / "corrupt.tar.gz"
            output = root / "map-ui"
            archive.write_bytes(b"0" * MANIFEST["upstream"]["archive_size_bytes"])

            result = prepare(output, archive)

            self.assertNotEqual(0, result.returncode)
            self.assertIn("checksum", result.stderr.lower())
            self.assertFalse(output.exists())

    # refuse to replace any existing output path
    def test_refuses_to_overwrite_existing_output(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            archive = root / "unused.tar.gz"
            output = root / "map-ui"
            output.mkdir()
            marker = output / "keep"
            marker.write_text("unchanged", encoding="utf-8")

            result = prepare(output, archive)

            self.assertNotEqual(0, result.returncode)
            self.assertIn("already exists", result.stderr.lower())
            self.assertEqual("unchanged", marker.read_text(encoding="utf-8"))

    # reproduce the complete production bundle without network access
    @unittest.skipUnless(
        PINNED_ARCHIVE is not None and PINNED_ARCHIVE.is_file(),
        "set ADSB_MAP_UI_ARCHIVE to the pinned archive for offline integration",
    )
    def test_prepares_pinned_bundle_offline(self):
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "map-ui"

            assert PINNED_ARCHIVE is not None
            result = prepare(output, PINNED_ARCHIVE)

            self.assertEqual(0, result.returncode, result.stderr)
            upstream = MANIFEST["upstream"]
            bundled_archive = output / upstream["archive_filename"]
            self.assertEqual(upstream["archive_sha256"], sha256(bundled_archive))
            self.assertEqual(PINNED_ARCHIVE.read_bytes(), bundled_archive.read_bytes())

            index = (output / "index.html").read_text(encoding="utf-8")
            self.assertNotIn("https://static.airplanes.live/db", index)
            self.assertIn("let databaseFolder = 'db-3.14.1715';", index)

            early_reference = re.search(r"early_[0-9a-f]{32}\.js", index)
            self.assertIsNotNone(early_reference)
            assert early_reference is not None
            early = (output / early_reference.group()).read_text(encoding="utf-8")
            self.assertNotIn("let aggregator = true;", early)
            self.assertIn("// use local receiver metadata rather than the public aggregator", early)
            self.assertIn("let aggregator = false;", early)

            expected_links = {
                "config.js": "/usr/local/share/tar1090/html-webroot/config.js",
                "db-3.14.1715": "/usr/local/share/tar1090/html-webroot/db-3.14.1715",
                "upintheair.json": "/usr/local/share/tar1090/html-webroot/upintheair.json",
            }
            # require exact absolute base-image integration links
            for name, target in expected_links.items():
                path = output / name
                self.assertTrue(path.is_symlink(), name)
                self.assertEqual(target, os.readlink(path))

            # require exact upstream cachebust names and source content
            for name, hashes in MANIFEST["assets"].items():
                stem, suffix = name.rsplit(".", 1)
                generated = f"{stem}_{hashes['md5']}.{suffix}"
                path = output / generated
                self.assertFalse((output / name).exists())
                self.assertEqual(hashes["sha256"], sha256(path))
                self.assertIn(generated, index)

            version = json.loads((output / "version.json").read_text(encoding="utf-8"))
            provenance = json.loads((output / "provenance.json").read_text(encoding="utf-8"))
            preparer = runpy.run_path(str(SCRIPT))
            self.assertEqual(upstream["commit"], version["upstream"]["commit"])
            self.assertEqual(upstream["version"], version["upstream"]["version"])
            self.assertEqual(upstream["archive_sha256"], version["upstream"]["archive_sha256"])
            self.assertEqual(MANIFEST["base_image_dependency"], version["base_image_dependency"])
            self.assertEqual(version, provenance)
            self.assertEqual("3.14.1817-airplanes-live-0c4e109", version["tar1090Version"])
            self.assertEqual("3.14.1715", version["databaseVersion"])
            self.assertEqual("early.js", version["local_patches"][0]["file"])
            self.assertEqual("let aggregator = true;", version["local_patches"][0]["source"])
            self.assertEqual(preparer["bundle_digest"](output), version["bundle_digest"])
            self.assertIn("GNU GENERAL PUBLIC LICENSE", (output / "LICENSE").read_text(encoding="utf-8"))
            self.assertTrue((output / "flags" / "3x2" / "US.svg").is_file())

            self.assertEqual(0o755, stat.S_IMODE(output.stat().st_mode))
            # keep every public directory and file nginx-readable under umask 077
            for path in output.rglob("*"):
                # never follow integration targets
                if path.is_symlink():
                    continue
                # distinguish static directories from files
                expected_mode = 0o755 if path.is_dir() else 0o644
                self.assertEqual(expected_mode, stat.S_IMODE(path.stat().st_mode), str(path))


if __name__ == "__main__":
    unittest.main()
